### ISSUE TITLE
running "markwiki -h",i met error,how to fix?

### ISSUE THREAD

**Issue by luckypoem** [mblayman/markwiki#19]
hi.
pip install markwiki

it shows:
...
Successfully installed MarkWiki Flask-Login Flask-WTF Whoosh WTForms
Cleaning up...
as3:~# markwiki -h
 * MARKWIKI_SETTINGS is not set (or has a bad file path). Using defaults ...
 * Creating the search index ...
Traceback (most recent call last):
  File "/usr/local/bin/markwiki", line 9, in <module>
    load_entry_point('MarkWiki==1.3', 'console_scripts', 'markwiki')()
  File "build/bdist.linux-i686/egg/pkg_resources.py", line 357, in load_entry_point
    """Return a readable file-like object for `resource_name`
  File "build/bdist.linux-i686/egg/pkg_resources.py", line 2394, in load_entry_point

  File "build/bdist.linux-i686/egg/pkg_resources.py", line 2108, in load
    def __eq__(self, other):
  File "/usr/local/lib/python2.7/site-packages/markwiki/__init__.py", line 37, in <module>
    import markwiki.views.core
  File "/usr/local/lib/python2.7/site-packages/markwiki/views/core.py", line 16, in <module>
    from markwiki.wiki import WikiPage
  File "/usr/local/lib/python2.7/site-packages/markwiki/wiki.py", line 8, in <module>
    from markwiki.renderer import render_markdown
  File "/usr/local/lib/python2.7/site-packages/markwiki/renderer.py", line 10, in <module>
    wiki_link_extension = MarkWikiLinkExtension()
  File "/usr/local/lib/python2.7/site-packages/markwiki/wikilinks.py", line 103, in __init__
    super(MarkWikiLinkExtension, self).__init__(configs={
TypeError: must be type, not classobj
as3:~#

**Comment by mblayman** [comment]
I cannot recreate the problem and I have not heard anything in over a year so I'm going to close this issue. If it's still a problem, please feel free to report in a new issue with additional information.
